_extends: guardrail:.github/release-drafter.yml
name-template: 'scala-pekko-http-v$RESOLVED_VERSION'
tag-template: 'scala-pekko-http-v$RESOLVED_VERSION'
tag-prefix: scala-pekko-http-v
include-paths:
  - "modules/scala-pekko-http/src/main/"
  - "project/src/main/scala/modules/scalaPekkoHttp.scala"
